### ISSUE TITLE
Please specify system requirements for the python server

### ISSUE THREAD

**Issue by zapta** [devanlai/webdfu#11]
This is what I get when I try to run. Are you using python 2? Can you provide a version for python 3?

/c/projects/webdfu/repo$ python --version
Python 3.8.5

/c/projects/webdfu/repo$ python SimpleSecureHTTPServer.py --cert server.pem --port 8000
Traceback (most recent call last):
  File "SimpleSecureHTTPServer.py", line 2, in <module>
    import BaseHTTPServer, SimpleHTTPServer
ModuleNotFoundError: No module named 'BaseHTTPServer'

**Comment by devanlai** [comment]
Hi @zapta, the original sample server is written for Python 2 - the modules are reorganized slightly for Python3. But you actually don't need to run an HTTPS server for development - Chrome will treat any "localhost" servers as secure contexts for development purposes even if it's served over HTTP.

I'll update the README accordingly in a bit. In the mean time, the standard snippet for running the simple HTTP server for Python3 should suffice:
```
python -m http.server
```

**Comment by zapta** [comment]
Hi @devanlai, the non https server worked and is a simpler solution, thanks.

BTW, I also found that this website http://pythonconverter.com/ converts correctly the .py server to python 3.  (Though I will not need it now).

This is a great project, exactly what I was looking for, as an easy firmware upgrade path for end users.
