### ISSUE TITLE
Support for esp32

### ISSUE THREAD

**Issue by LuC-9** [devanlai/webdfu#13]
How Can I Use It For ESP32 and ESP 8266

**Comment by devanlai** [comment]
Hi @LuC-9,
The ESP32 and ESP8266 do not have native USB support and thus do not use the USB DFU protocol to load firmware. (The ESP32-S2 does support USB DFU and I believe it has been tested successfully with webdfu).

For the ESP32 and ESP8266, you might like to try out Adafruit's WebSerial implementation of ESPTool that should work with the ESP32:
https://github.com/adafruit/Adafruit_WebSerial_ESPTool
